apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    service: backend-feed
    name: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      service: backend-feed
  template:
    metadata:
      labels:
        service: backend-feed
    spec:
      containers:
        - image: docker.io/femo123456/udagram-api-feed:v1
          name: backend-feed
          imagePullPolicy: Always
          env:
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: URL
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: AWS_BUCKET
            - name: AWS_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: AWS_PROFILE
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: AWS_REGION
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: JWT_SECRET
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: myconfig
                  key: POSTGRES_HOST
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgrescred
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: postgrescred
                  key: POSTGRES_USERNAME
          volumeMounts:
            - name: mysecret
              mountPath: "/root/.aws/"
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: mysecret
          secret:
            secretName: mysecret
